version: '3'

services:
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./log/certbot:/var/log/letsencrypt
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  db:
    image: postgres:10
    restart: unless-stopped
    volumes:
      - /opt/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=entrar
      - POSTGRES_USER=scaleusr
      - POSTGRES_PASSWORD=Entrar955
  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    restart: unless-stopped
    volumes:
      - /opt/redis:/data
  scalelite-api:
    image: blindsidenetwks/scalelite:${SCALELITE_TAG:-v1}-api
    container_name: scalelite-api
    restart: unless-stopped
    env_file: /etc/default/scalelite
    volumes:
      - ./log/scalelite/:/app/log
      - ${SCALELITE_RECORDING_DIR-/mnt/scalelite-recordings/var/bigbluebutton}:/var/bigbluebutton
    depends_on:
      - db
      - redis
  scalelite-nginx:
    image: blindsidenetwks/scalelite:${SCALELITE_TAG}-nginx
    restart: unless-stopped
    container_name: scalelite-nginx
    env_file: /etc/default/scalelite
    depends_on:
      - scalelite-api
      - db
      - redis
    volumes:
      - ./log/nginx/:/var/log/nginx
      - ./data/certbot/conf:/etc/nginx/ssl
      - ./data/certbot/www:/var/www/certbot
      - ./data/nginx/scalelite:/etc/nginx/conf.d/scalelite
      - ${SCALELITE_RECORDING_DIR-/mnt/scalelite-recordings/var/bigbluebutton}/published:/var/bigbluebutton/published
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_SSL=${NGINX_SSL-true}
      - URL_HOST=${URL_HOST}
  scalelite-poller:
    image: blindsidenetwks/scalelite:${SCALELITE_TAG}-poller
    container_name: scalelite-poller
    restart: unless-stopped
    env_file: /etc/default/scalelite
    depends_on:
      - scalelite-api
      - db
      - redis
  scalelite-recording-importer:
    image: blindsidenetwks/scalelite:${SCALELITE_TAG}-recording-importer
    container_name: scalelite-recording-importer
    restart: unless-stopped
    env_file: /etc/default/scalelite
    volumes:
      - ${SCALELITE_RECORDING_DIR}:/var/bigbluebutton
    depends_on:
      - scalelite-api
      - db
      - redis
